# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_broadcast_channel"
version = "0.44.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Implementation of BroadcastChannel API for Deno"

[lib]
path = "lib.rs"

[features]
standalone = ["deno_core/standalone"]

[dependencies]
async-trait = "0.1"
deno_core = { version = "0.132.0", path = "../../core" }
tokio = { version = "1.17", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4"] }
