# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_url"
version = "0.50.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "URL API implementation for Deno"

[lib]
path = "lib.rs"

[features]
standalone = ["deno_core/standalone"]

[dependencies]
deno_core = { version = "0.132.0", path = "../../core" }
serde = { version = "1.0.129", features = ["derive"] }
serde_repr = "0.1.7"
urlpattern = "0.1.6"

[dev-dependencies]
deno_bench_util = { version = "0.44.0", path = "../../bench_util" }
deno_webidl = { version = "0.50.0", path = "../webidl" }

[[bench]]
name = "url_ops"
harness = false
