# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
authors = ["the Deno authors"]
description = "Implementation of WebSocket API for Deno"
edition = "2021"
license = "MIT"
name = "deno_websocket"
readme = "README.md"
repository = "https://github.com/denoland/deno"
version = "0.67.0"

[lib]
path = "lib.rs"

[features]
standalone = ["deno_core/standalone"]

[dependencies]
deno_core = {version = "0.144.0", path = "../../core"}
deno_tls = {version = "0.49.0", path = "../tls"}
http = "0.2.6"
hyper = {version = "0.14.18"}
serde = {version = "1.0.136", features = ["derive"]}
tokio = {version = "1.17", features = ["full"]}
tokio-rustls = "0.23.3"
tokio-tungstenite = {version = "0.16.1", features = ["rustls-tls-webpki-roots"]}
