# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.
[package]
name = "deno_core"
version = "0.132.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "A modern JavaScript/TypeScript runtime built with V8, Rust, and Tokio"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0.55"
deno_ops = { path = "../ops", version = "0.10.0" }
futures = "0.3.21"
indexmap = "1.7.0"
libc = "0.2.121"
log = "0.4.14"
once_cell = "1.10.0"
parking_lot = "0.12.0"
pin-project = "1.0.7"
serde = { version = "1.0.129", features = ["derive"] }
serde_json = { version = "1.0.66", features = ["preserve_order"] }
serde_v8 = { version = "0.43.0", path = "../serde_v8" }
sourcemap = "=6.0.1"
url = { version = "2.2.2", features = ["serde"] }
v8 = "0.42.0"

[features]
standalone = []

[[example]]
name = "http_bench_json_ops"
path = "examples/http_bench_json_ops.rs"

# These dependencies are only used for the 'http_bench_*_ops' examples.
[dev-dependencies]
deno_ast = { version = "0.14.0", features = ["transpiling"] }
tokio = { version = "1.17", features = ["full"] }
