# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.
[package]
authors = ["the Deno authors"]
description = "A modern JavaScript/TypeScript runtime built with V8, Rust, and Tokio"
edition = "2021"
license = "MIT"
name = "deno_core"
readme = "README.md"
repository = "https://github.com/denoland/deno"
version = "0.144.0"

[lib]
path = "lib.rs"

[features]
default = ["v8_use_custom_libcxx"]
standalone = []
v8_use_custom_libcxx = ["v8/use_custom_libcxx"]

[dependencies]
anyhow = "1.0.57"
deno_ops = {path = "../ops", version = "0.22.0"}
futures = "0.3.21"
indexmap = "1.8.1"
libc = "0.2.126"
log = "0.4.16"
once_cell = "1.10.0"
parking_lot = "0.12.0"
pin-project = "1.0.11"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = {version = "1.0.79", features = ["preserve_order"]}
serde_v8 = {version = "0.55.0", path = "../serde_v8"}
sourcemap = "=6.0.1"
url = {version = "2.2.2", features = ["serde"]}
v8 = {version = "0.47.1", default-features = false}

[[example]]
name = "http_bench_json_ops"
path = "examples/http_bench_json_ops.rs"

# These dependencies are only used for the 'http_bench_*_ops' examples.
[dev-dependencies]
deno_ast = {version = "0.17.0", features = ["transpiling"]}
tokio = {version = "1.19", features = ["full"]}
