# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_fetch"
version = "0.73.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Fetch API implementation for Deno"

[lib]
path = "lib.rs"

[features]
standalone = ["deno_core/standalone"]

[dependencies]
bytes = "1.1.0"
data-url = "0.1.0"
deno_core = { version = "0.132.0", path = "../../core" }
deno_tls = { version = "0.37.0", path = "../tls" }
dyn-clone = "1"
http = "0.2.4"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli"] }
serde = { version = "1.0.129", features = ["derive"] }
tokio = { version = "1.17", features = ["full"] }
tokio-stream = "0.1.7"
tokio-util = { version = "0.7.0", features = ["io"] }
