# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webstorage"
version = "0.45.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Implementation of WebStorage API for Deno"

[lib]
path = "lib.rs"

[features]
standalone = ["deno_core/standalone"]

[dependencies]
deno_core = { version = "0.132.0", path = "../../core" }
deno_web = { version = "0.81.0", path = "../web" }
rusqlite = { version = "0.27.0", features = ["unlock_notify", "bundled"] }
serde = { version = "1.0.129", features = ["derive"] }
