# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
authors = ["the Deno authors"]
description = "Collection of Web APIs"
edition = "2021"
license = "MIT"
name = "deno_web"
readme = "README.md"
repository = "https://github.com/denoland/deno"
version = "0.93.0"

[lib]
path = "lib.rs"

[features]
standalone = ["deno_core/standalone"]

[dependencies]
async-trait = "0.1.51"
base64-simd = "0.6.2"
deno_core = {version = "0.144.0", path = "../../core"}
encoding_rs = "0.8.31"
flate2 = "1"
serde = "1.0.136"
tokio = {version = "1.17", features = ["full"]}
uuid = {version = "1.0.0", features = ["v4", "serde"]}

[dev-dependencies]
deno_bench_util = {version = "0.56.0", path = "../../bench_util"}
deno_url = {version = "0.62.0", path = "../url"}
deno_webidl = {version = "0.62.0", path = "../webidl"}

[[bench]]
harness = false
name = "encoding"

[[bench]]
harness = false
name = "timers_ops"
