# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
authors = ["the Deno authors"]
description = "HTTP server implementation for Deno"
edition = "2021"
license = "MIT"
name = "deno_http"
readme = "README.md"
repository = "https://github.com/denoland/deno"
version = "0.56.0"

[lib]
path = "lib.rs"

[features]
standalone = ["deno_core/standalone"]

[[bench]]
harness = false
name = "compressible"

[dependencies]
async-compression = {version = "0.3.12", features = ["tokio", "brotli", "gzip"]}
base64 = "0.13.0"
brotli = "3.3.4"
bytes = "1"
cache_control = "0.2.0"
deno_core = {version = "0.144.0", path = "../../core"}
deno_websocket = {version = "0.67.0", path = "../websocket"}
flate2 = "1.0.23"
fly-accept-encoding = "0.2.0"
hyper = {version = "0.14.18", features = ["server", "stream", "http1", "http2", "runtime"]}
mime = "0.3.16"
percent-encoding = "2.1.0"
phf = {version = "0.10", features = ["macros"]}
ring = "0.16.20"
serde = {version = "1.0.136", features = ["derive"]}
tokio = {version = "1.17", features = ["full"]}
tokio-util = {version = "0.7.1", features = ["io"]}

[dev-dependencies]
bencher = "0.1"
