# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_http"
version = "0.44.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "HTTP server implementation for Deno"

[lib]
path = "lib.rs"

[features]
standalone = ["deno_core/standalone"]

[[bench]]
name = "compressible"
harness = false

[dependencies]
async-compression = { version = "0.3.1", features = ["tokio", "brotli", "gzip"] }
base64 = "0.13.0"
brotli = "3.3.3"
bytes = "1"
cache_control = "0.2.0"
deno_core = { version = "0.132.0", path = "../../core" }
deno_websocket = { version = "0.55.0", path = "../websocket" }
flate2 = "1.0.22"
fly-accept-encoding = "0.2.0-alpha.5"
hyper = { version = "0.14.9", features = ["server", "stream", "http1", "http2", "runtime"] }
mime = "0.3.16"
percent-encoding = "2.1.0"
phf = { version = "0.10", features = ["macros"] }
ring = "0.16.20"
serde = { version = "1.0.129", features = ["derive"] }
tokio = { version = "1.17", features = ["full"] }
tokio-util = { version = "0.7.0", features = ["io"] }

[dev-dependencies]
bencher = "0.1"
